### ISSUE TITLE
How does javafx integrate jcef?

### ISSUE THREAD

**Issue by fendo8888** [jcefbuild/jcefbuild#10]
How does javafx integrate jcef?，Or how to achieve javafx integration jcef?

**Comment by smac89** [comment]
This is something I don't have control over, but I am also interested in seeing this becoming a reality. At the moment, there are people making [significant strides](https://github.com/eclipse-efx/efxclipse-drift) in [different](https://github.com/dzikoysk/pandomium) ways to achieve this.

This repository is mainly concerned with building jcef, so that developers can focus on using it.

There is also an [issue](https://bitbucket.org/chromiumembedded/java-cef/issues/163/provide-javafx-node-for-jcef) over on the official bitbucket repo for jcef which addresses the need for a javafx node.
